### ISSUE TITLE
doesn't work on 1.20.1

### ISSUE THREAD

**Issue by arturdvevo** [GreeFoxTheDev/Copper-Items#1]
works on 1.20, not on 1.20.1, pls fix!!!

**Comment by GreeFoxTheDev** [comment]
@spront ty for feedback, what exactly is the console saying? Or the textures don't work?

**Comment by arturdvevo** [comment]
console doesn't say anything other than the items are enabled, but they aren't craftable or show up in any menus.

**Comment by arturdvevo** [comment]
same thing happens with the daggers and katana plugins too.

**Comment by GreeFoxTheDev** [comment]
Ok that's weird, can we chat on Discord? I'm _greefox_.

**Comment by arturdvevo** [comment]
ok

**Comment by GreeFoxTheDev** [comment]
I don't know what the problem was, but the new version (of all my plugins) works - download on [Modrinth](https://modrinth.com/plugin/copper-items)
